# AstroCare Remote Health - Configurações da Aplicação

# Datasource Oracle FIAP
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=RM567980
quarkus.datasource.password=210504
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl

# HTTP
quarkus.http.port=8080

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS

# Logs
quarkus.log.level=INFO
